services:
  postgres:
    image: postgres:14
    container_name: kw_ic_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: whffu18
    ports:
      - "5418:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kw_ic_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: kw_ic_app
    restart: always
    ports:
      - "35504:35504"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DBNAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=whffu18
      - APP_PORT=35504
      - APP_HOST=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kw_ic_network

volumes:
  postgres_data:

networks:
  kw_ic_network:
    driver: bridge
